server:
  port: 8080
spring:
  application:
    name: LikeGateway
  cloud:
    nacos:
      discovery:
        server-addr: 124.71.183.250:8848
    gateway:
      routes:
        - id: likeapi
          uri: lb://Consumer
          predicates:
          - Path=/like/**
          filters:
          - StripPrefix=1    #表示路由时会去除的路径级别


        - id: userapi
          uri: lb://Consumer
          predicates:
          - Path=/user/**
          filters:
          - StripPrefix=1    #表示路由时会去除的路径级别