server:
    port: 8081
spring:
    application:
        name: Provider #服务名称 唯一
    cloud:
        nacos:
            discovery:
                server-addr: 124.71.183.250:8848
    datasource:
        url: jdbc:mysql://localhost:3306/day_047_homework?serverTimezone=Asia/Shanghai
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: root
        type: com.alibaba.druid.pool.DruidDataSource

